---
name: 'Build Docker Image & Update Application Helm Chart Values'
on:
  push:
    branches:
      - main
env:
  DOCKER_ID: ${{ secrets.DOCKER_ID }}
  DOCKER_PW: ${{ secrets.DOCKER_PW }}
  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
#  DATREE_TOKEN: ${{ secrets.DATREE_TOKEN }}
jobs:
  build_image:
    name: Build Image & Update Helm Chart Values
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    steps:     
      - uses: actions/checkout@v3
      # Install Helm
      - name: Install Helm
        run: |
          curl -sSL https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
          helm version --short
      # Login to Docker registry
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_PW }}
      # Install yq
      - name: Install yq 
        run: |
          wget https://github.com/mikefarah/yq/releases/download/v4.12.0/yq_linux_amd64 -O /usr/bin/yq && chmod +x /usr/bin/yq
          yq --version
      # Build and test application
      - name: Build, test and push to Docker Hub
        run: |
          echo Build started on `date`
          echo Building the Docker image...
          CONTAINER_IMAGE_TAG="$(cat version)"
          docker build -t rmahiquesuse/webphotobook_demo:$CONTAINER_IMAGE_TAG . 
          echo Pushing the Docker image...
          docker push rmahiquesuse/webphotobook_demo:$CONTAINER_IMAGE_TAG
      # Clone git repository with Helm charts, update and push changes
      - name: Update image tag in Helm git repo 
        run: | 
          CONTAINER_IMAGE_TAG="$(cat version)"
          echo New container image tag: $CONTAINER_IMAGE_TAG
          echo Create temporary folder to clone the repo into...
          TEMP_FOLDER="$(mktemp -d)" 
          echo Clone the repository...
          git clone -b main "https://rmahique:${ACCESS_TOKEN}@github.com/rmahique/webphotobook_demo.git" ${TEMP_FOLDER} 
          cd ${TEMP_FOLDER}/helm/webphotobook 
          ls
          echo Update Helm chart values-dev with new image tag digest
          IMAGE_TAG_DIGEST=$(docker manifest inspect --verbose rmahiquesuse/webphotobook_demo:$CONTAINER_IMAGE_TAG | jq -r '.Descriptor.digest')
          echo New container image digest: $IMAGE_TAG_DIGEST
          IMAGE_TAG_DIGEST=$IMAGE_TAG_DIGEST yq e -i '.orders.newDeployment.imageTag = env(IMAGE_TAG_DIGEST)' ./values.yaml
          echo 'Container image tag updated in values.yaml' 
          cd ../../
          git config user.name "rmahique-github" 
          git add .  
          git commit -m "refactor - updated Helm chart values for dev environment with container image - $CONTAINER_IMAGE_TAG [skip ci]"
          git push -u origin main
